spring.application.name=jira-gifthub

spring.datasource.url=jdbc:mysql://localhost:3306/jira_gifthub
spring.datasource.username=root
spring.datasource.password=@a0395053636#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true